# Generated by Django 4.2 on 2025-08-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_subject_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='student',
            new_name='creared_by',
        ),
    ]
